name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck
